---
- name: Установка Kibana
  hosts: kibana
  become: yes
  tasks:

    - name: Добавление репозитория Elastic от Yandex Mirror
      apt_repository:
        repo: "deb [trusted=yes] https://mirror.yandex.ru/mirrors/elastic/7/ stable main"
        filename: "elastic-7.x"
        state: present

    - name: Обновление списка пакетов
      apt:
        update_cache: yes

    - name: Установка Kibana
      apt:
        name: kibana
        state: present

    - name: Настройка Kibana подключения к Elasticsearch
      blockinfile:
        path: /etc/kibana/kibana.yml
        block: |
          server.host: "0.0.0.0"
          elasticsearch.hosts: ["http://elastic.ru-central1.internal:9200"]
          elasticsearch.username: "elastic"
          elasticsearch.password: "lup3RcsOaHaSwoJ1zD44"

    - name: Включение и запуск Kibana
      systemd:
        name: kibana
        enabled: yes
        state: started