---
- name: Install and configure Nginx on Ubuntu 22.04
  hosts: webservers
  become: yes
  vars:
    custom_message: "Welcome to my Nginx server!"

  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Ensure Nginx is running and enabled
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Create custom index.html
      copy:
        content: |
          <!DOCTYPE html>
          <html>
          <head>
              <title>My Nginx server</title>
              <style>
                  body {
                      font-family: Arial, sans-serif;
                      text-align: center;
                      margin-top: 50px;
                      background-color: #f0f0f0;
                  }
                  h1 {
                      color: #333;
                  }
              </style>
          </head>
          <body>
              <h1>{{ custom_message }}</h1>
              <p>Everything will be fine!</p>
          </body>
          </html>
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: '0644'

    - name: Adjust Nginx configuration
      blockinfile:
        path: /etc/nginx/sites-available/default
        block: |
          server {
              listen 80 default_server;
              listen [::]:80 default_server;
              root /var/www/html;
              index index.html;
              location / {
                  try_files $uri $uri/ =404;
              }
          }
        marker: "# {mark} ANSIBLE MANAGED BLOCK - NGINX CONFIG"

